name: Build and push website image

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.12.1
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: pnpm
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Froze lockfile
        run: pnpm install --frozen-lockfile
        working-directory: .
      - name: Run pnpm build
        run: |
          pnpm build
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build and push
        id: docker_build
        uses: docker/build-push-action
        with:
          file: Dockerfile
          platforms: linux/arm64
          push: true
          tags: bytebase/website
      - name: Image digest
        run: echo "Successfully pushed bytebase/website" ${{ steps.docker_build.outputs.digest }}
