name: Build and push website image

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.12.1
      - uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: pnpm
          cache-dependency-path: 'frontend/pnpm-lock.yaml'
      - run: pnpm install --frozen-lockfile
        working-directory: frontend
      - name: Run pnpm build
        run: |
          pnpm build
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: depot/setup-action@v1
      - name: Docker build and push
        id: docker_build
        uses: depot/build-push-action@v1
        with:
          context: .
          project: ${{ secrets.DEPOT_PROJECT}}
          token: ${{ secrets.DEPOT_TOKEN }}
          file: scripts/Dockerfile.depot
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bytebase/website
      - name: Image digest
        run: echo "Successfully pushed bytebase/website" ${{ steps.docker_build.outputs.digest }}
